server:
  port: ${PORT:${SERVER_PORT:0}}
message: Configuracion de user en el servidor levantado!
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: 12345678
    url: jdbc:mysql://localhost:3306/proyectoustay?serverTimezone=UTC
    username: root
  jpa:
    hibernate:
      ddl-auto: update
      database-platform: org.hibernate.dialect.MySQLDialect
  application:
    name: user-service
  cloud:
    config:
      uri: http://localhost.8860
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceurl:
      defaultZone: http://localhost:8762/eureka/
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
